
import React from 'react';
import { Tool, ToolType } from './types';

export const TOOLS: Tool[] = [
  {
    id: ToolType.ASSISTANT,
    name: 'Smart Assistant',
    description: 'General purpose AI for answering any question, drafting emails, or brainstorming.',
    icon: '✨',
    color: 'bg-indigo-500',
  },
  {
    id: ToolType.TYPING_TESTER,
    name: 'Typing Speed Lab',
    description: 'Measure your words per minute and accuracy with real-time feedback and AI challenges.',
    icon: '⌨️',
    color: 'bg-amber-600',
  },
  {
    id: ToolType.ERD_STUDIO,
    name: 'ERD Studio',
    description: 'Generate professional SQLite Entity Relationship Diagrams from descriptions or SQL code.',
    icon: '📊',
    color: 'bg-teal-600',
  },
  {
    id: ToolType.WEBSITE_BUILDER,
    name: 'Website Builder',
    description: 'Describe your vision and watch AI build a responsive HTML/CSS/JS website in seconds.',
    icon: '🏗️',
    color: 'bg-indigo-700',
  },
  {
    id: ToolType.URL_TOOL,
    name: 'URL Studio',
    description: 'Encode or decode special characters in strings to make them URL-safe.',
    icon: '🔗',
    color: 'bg-blue-500',
  },
  {
    id: ToolType.IMAGE_TO_PDF,
    name: 'Image to PDF',
    description: 'Upload multiple images in sequence and export them as a single document.',
    icon: '🖼️',
    color: 'bg-violet-500',
  },
  {
    id: ToolType.SHOPPING_LIST,
    name: 'Shopping List',
    description: 'Track items, manage quantities, and automatically calculate your total budget.',
    icon: '🛒',
    color: 'bg-emerald-600',
  },
  {
    id: ToolType.SMART_NOTEPAD,
    name: 'Smart Notepad',
    description: 'A distraction-free writing space with AI tools to polish, expand, or summarize your notes.',
    icon: '📝',
    color: 'bg-orange-500',
  },
  {
    id: ToolType.SIMPLE_COUNTER,
    name: 'Counter Lab',
    description: 'A simple yet powerful tool for tracking tallies, inventory, or repetitions with custom steps.',
    icon: '🔢',
    color: 'bg-blue-600',
  },
  {
    id: ToolType.QR_GENERATOR,
    name: 'QR Studio',
    description: 'Instantly generate customizable QR codes for URLs, text, or contact information.',
    icon: '📱',
    color: 'bg-violet-600',
  },
  {
    id: ToolType.TODO_LIST,
    name: 'AI Task Planner',
    description: 'Manage your tasks with AI-powered sub-task suggestions and breakdown logic.',
    icon: '✅',
    color: 'bg-blue-500',
  },
  {
    id: ToolType.RESEARCHER,
    name: 'Smart Researcher',
    description: 'Real-time web search for the latest news, events, and factual data with citations.',
    icon: '🔍',
    color: 'bg-teal-500',
  },
  {
    id: ToolType.CODE_PLAYGROUND,
    name: 'Code Playground',
    description: 'Live multi-language compiler and HTML/JS previewer with AI debugging support.',
    icon: '🚀',
    color: 'bg-slate-800',
  },
  {
    id: ToolType.VOICE_HUB,
    name: 'Voice Hub',
    description: 'Convert any text into natural, human-like speech with various AI voices.',
    icon: '🔊',
    color: 'bg-cyan-600',
  },
  {
    id: ToolType.DOC_STUDIO,
    name: 'Doc Studio',
    description: 'Convert text to PDF or extract content from PDF documents instantly.',
    icon: '📂',
    color: 'bg-purple-600',
  },
  {
    id: ToolType.IMAGE_GEN,
    name: 'Visual Creator',
    description: 'Transform text descriptions into stunning high-quality images instantly.',
    icon: '🎨',
    color: 'bg-rose-500',
  },
  {
    id: ToolType.TEXT_ANALYSIS,
    name: 'Text Engine',
    description: 'Summarize long documents, extract key insights, or translate content.',
    icon: '📄',
    color: 'bg-emerald-500',
  },
  {
    id: ToolType.CONVERTER,
    name: 'Conversion Tool',
    description: 'Convert units for mass, length, temperature, and more.',
    icon: '⚖️',
    color: 'bg-indigo-600',
  },
  {
    id: ToolType.PASSWORD_GEN,
    name: 'Password Generator',
    description: 'Create secure passwords for your accounts.',
    icon: '🔑',
    color: 'bg-amber-500',
  }
];
